export { DeviceCard } from "./components/device-card";
export { DeviceStatusBadge, OnlineBadge } from "./components/device-status-badge";
export { PageDevice } from "./detail/page-device";
export { SectionActivity } from "./detail/sections/section-activity";
export { SectionApps } from "./detail/sections/section-apps";
export { SectionBackups } from "./detail/sections/section-backups";
export { SectionFiles } from "./detail/sections/section-files";
export { SectionOverview } from "./detail/sections/section-overview";
export { SectionSettings } from "./detail/sections/section-settings";
export { SectionStorage } from "./detail/sections/section-storage";
export { SectionTerminal } from "./detail/sections/section-terminal";
export { PageDevices } from "./list/page-devices";
