package com.bancada.hyperv;

import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;

/**
 * The cloud-init NoCloud seed of a new virtual machine: who logs in, with which password, the key
 * the panel uses, the SSH host key generated by the panel (so the machine is known before it ever
 * boots), a fixed address on the Bancada network and the Hyper-V guest tools.
 *
 * @param instanceId     changes on every reinstall, so cloud-init runs again
 * @param hostPrivateKey PEM of the SSH host key the machine must present
 */
public record CloudInit(String hostname, String instanceId, String username, String password, String adminGroup,
                        String panelPublicKey, String hostPrivateKey, String hostPublicKey, String macAddress,
                        String address, int prefixLength, String gateway, List<String> dnsServers) {

    public CloudInit {
        if (password.contains("\n") || password.contains("\r")) {
            throw new IllegalArgumentException("A senha não pode ter quebra de linha.");
        }
    }

    /** File name to content, as the seed ISO carries them. */
    public Map<String, String> files() {
        Map<String, String> files = new LinkedHashMap<>();
        files.put("meta-data", "instance-id: " + instanceId + "\nlocal-hostname: " + hostname + "\n");
        files.put("user-data", userData());
        files.put("network-config", networkConfig());
        return files;
    }

    private String userData() {
        StringBuilder yaml = new StringBuilder()
            .append("#cloud-config\n")
            .append("hostname: ").append(hostname).append('\n')
            .append("manage_etc_hosts: true\n")
            .append("ssh_pwauth: true\n")
            .append("disable_root: false\n")
            // the host key is the panel's: new keys would break the pinning of the device
            .append("ssh_deletekeys: true\n")
            .append("ssh_genkeytypes: []\n")
            .append("ssh_keys:\n")
            .append("  rsa_private: |\n").append(indent(hostPrivateKey.strip(), "    ")).append('\n')
            .append("  rsa_public: ").append(hostPublicKey.strip()).append('\n')
            .append("users:\n")
            .append("  - default\n")
            .append("  - name: ").append(username).append('\n')
            .append("    groups: [").append(adminGroup).append("]\n")
            .append("    shell: /bin/bash\n")
            .append("    sudo: \"ALL=(ALL) ALL\"\n")
            .append("    lock_passwd: false\n")
            .append("chpasswd:\n")
            .append("  expire: false\n")
            .append("  users:\n")
            .append("    - name: ").append(username).append('\n')
            .append("      password: ").append(singleQuoted(password)).append('\n')
            .append("      type: text\n")
            // the panel manages the machine as root, with its own key only
            .append("write_files:\n")
            .append("  - path: /root/.ssh/authorized_keys\n")
            .append("    permissions: '0600'\n")
            .append("    owner: root:root\n")
            .append("    content: |\n")
            .append("      ").append(panelPublicKey.strip()).append('\n')
            .append("growpart:\n")
            .append("  mode: auto\n")
            .append("  devices: ['/']\n")
            // guest tools: address report, clean shutdown and consistent backups (fsfreeze)
            .append("package_update: false\n")
            .append("runcmd:\n")
            .append("  - [sh, -c, 'if command -v apt-get >/dev/null; then DEBIAN_FRONTEND=noninteractive apt-get install -y ")
            .append("hyperv-daemons || apt-get install -y linux-cloud-tools-virtual; ")
            .append("elif command -v dnf >/dev/null; then dnf install -y hyperv-daemons; fi; true']\n");
        return yaml.toString();
    }

    private String networkConfig() {
        StringBuilder yaml = new StringBuilder()
            .append("version: 2\n")
            .append("ethernets:\n")
            .append("  eth0:\n")
            .append("    match:\n")
            .append("      macaddress: '").append(macAddress.toLowerCase()).append("'\n")
            .append("    set-name: eth0\n")
            .append("    addresses: [").append(address).append('/').append(prefixLength).append("]\n")
            .append("    routes:\n")
            .append("      - to: 0.0.0.0/0\n")
            .append("        via: ").append(gateway).append('\n')
            .append("    nameservers:\n")
            .append("      addresses: [").append(String.join(", ", dnsServers)).append("]\n");
        return yaml.toString();
    }

    private static String indent(String text, String prefix) {
        return prefix + text.replace("\r\n", "\n").replace("\n", "\n" + prefix);
    }

    private static String singleQuoted(String value) {
        return "'" + value.replace("'", "''") + "'";
    }
}
